export enum MinigameType {

  BountyHunterHunter = 1,
  BountyHunterRogue = 2,

  ClueScrollsAll = 3,
  ClueScrollsBeginner = 4,
  ClueScrollsEasy = 5,
  ClueScrollsMedium = 6,
  ClueScrollsHard = 7,
  ClueScrollsElite = 8,
  ClueScrollsMaster = 9,


  AbyssalSire = 12,
  AlchemicalHydra = 13,
  BarrowsChests = 14,
  Bryophyta = 15,
  Callisto = 16,
  Cerberus = 17,
  ChambersOfXeric = 18,
  ChambersOfXericChallengeMode = 19,
  ChaosElemental = 20,
  ChaosFanatic = 21,
  CommanderZilyana = 22,
  CorporealBeast = 23,
  CrazyArchaeologist = 24,
  DagannothPrime = 25,
  DagannothRex = 26,
  DagannothSupreme = 27,
  DerangedArchaeologist = 28,
  GeneralGraador = 29,
  GiantMole = 30,
  GrotesqueGuardians = 31,
  Hespori = 32,
  KalphiteQueen = 33,
  
  LastManStanding = 10,
  Soulwars = 11,

  KingBlackDragon = 34,
  Kraken = 35,
  KreeArra = 36,
  KrilTsutsaroth = 37,
  Mimic = 38,
  Nightmare = 39,
  Obor = 40,
  Sarachnis = 41,
  Scorpia = 42,
  Skotizo = 43,
  TheGauntlet = 44,
  TheCorruptedGauntlet = 45,
  TheatreOfBlood = 46,
  ThermonuclearSmokeDevil = 47,
  TzKalZuk = 48,
  TzTokJad = 49,
  Venenatis = 50,
  Vetion = 51,
  Vorkath = 52,
  Wintertodt = 53,
  Zalcano = 54,
  Zulrah = 55,
}